name: material_color_scheme
description: A tool for easily making material and flutter color schemes.
version: 0.0.3
author: Stefan Rusek <stefan@ergonlabs.com>
homepage: https://github.com/stefanrusek/material_color_scheme

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
